version: '3.8'

services:
  app:
    image: dotnet-postgres-vue:0.01
    
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - local-postgres
    
    # Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
    # user: root

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    #environment:
    # - ASPNETCORE_ENVIRONMENT=Development
    # - ASPNETCORE_URLS=https://+:7262;http://+:5188

  postgres:
    container_name: postgresdb_vue
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - local-postgres
    
  pgadmin:
    container_name: pgadmin4_vue
    image: dpage/pgadmin4:6
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin-conf:/etc/pgadmin
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - local-postgres

volumes:
  postgres-data:
  pgadmin-data:
  pgadmin-conf:

networks:
  local-postgres:
 